name: Vulnerability Check

on:
  - push
  - pull_request

jobs:
  vulnerability_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install safety
      - name: Check for vulnerabilities
        run: |
          safety check
          # Add any custom validation or processing of the vulnerability report here
